import './style.css';

const KEY='claude-premium-chats', MODEL='claude-premium-model', THEME='claude-premium-theme';
const state={chats:read(KEY,[]),active:null,model:localStorage.getItem(MODEL)||'auto/best-coding',sending:false,controller:null,files:[],fileData:new Map()};
const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.chats));localStorage.setItem(MODEL,state.model)}
function chat(){return state.chats.find(x=>x.id===state.active)||null}
function esc(x){return String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function logo(n=24){return `<img class="claude-logo" width="${n}" height="${n}" src="/claude-symbol.svg" alt="">`}
function md(t){let h=esc(t||'');h=h.replace(/!\[([^\]]*)\]\((https?:\/\/[^\s)]+)\)/g,'<img class="md-image" src="$2" alt="$1">');h=h.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>');const lines=h.split('\n'),out=[];let code=false,b=[],lang='';for(const l of lines){if(l.startsWith('```')){if(code){out.push(`<div class="code-card"><div class="code-head"><span>${esc(lang||'code')}</span><button class="copy" type="button">Copy</button></div><pre><code>${b.join('\n')}</code></pre></div>`);code=false;b=[]}else{code=true;b=[];lang=l.slice(3).trim()}continue}if(code){b.push(l);continue}if(/^#{1,3}\s/.test(l)){const n=l.match(/^#+/)[0].length;out.push(`<h${n}>${l.slice(n+1)}</h${n}>`)}else if(/^[-*]\s/.test(l))out.push(`<li>${l.slice(2)}</li>`);else if(l.trim())out.push(`<p>${l.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}</p>`)}return out.join('')}
function render(){const c=chat();document.documentElement.classList.toggle('dark',localStorage.getItem(THEME)!=='light');$('#root').innerHTML=`<div class="app"><aside class="sidebar"><div class="sidebar-main"><div class="brand"><img src="/claude-symbol.svg" class="brand-symbol" alt=""><b>Claude</b><button id="collapse" aria-label="Collapse">‹</button></div><button id="new" class="new-chat"><span>＋</span><strong>New chat</strong></button><nav class="primary-nav"><button class="nav active"><span>◌</span> Chats</button><button class="nav"><span>▦</span> Projects</button></nav><div class="recent">Recent</div><div class="chat-list">${state.chats.length?state.chats.map(x=>`<button class="chat ${x.id===state.active?'active':''}" data-chat="${x.id}"><span>${esc(x.title||'New chat')}</span><i data-del="${x.id}">×</i></button>`).join(''):'<div class="empty">Your conversations will appear here.</div>'}</div></div><div class="side-bottom"><button class="account"><strong>R</strong><span>Ranjith<small>Local workspace</small></span><em>•••</em></button></div></aside><main class="main"><header class="topbar"><button id="mobile" class="mobile">☰</button><button id="model" class="model"><span>${esc(state.model)}</span><small>⌄</small></button><div class="top-actions"><button id="clear" class="top-icon" title="Clear chat">⌫</button><button id="theme" class="top-icon" title="Toggle theme">◐</button></div></header><div id="model-menu" class="model-menu hidden"><button data-model="auto/best-coding">${logo(20)}<span>auto/best-coding</span></button></div><section id="conversation" class="conversation">${c?.messages?.length?c.messages.map(renderMsg).join(''):welcome()}</section><div class="composer-zone"><div class="attachments">${state.files.map(fileChip).join('')}</div><form id="composer" class="composer"><textarea id="prompt" placeholder="How can I help you today?" rows="1" ${state.sending?'disabled':''}></textarea><div class="composer-row"><div class="tools"><label title="Attach files">＋<input id="file" type="file" multiple accept="image/*,video/*,.pdf,.txt,.md,.csv,.json,.js,.ts,.py,.java,.zip,.doc,.docx,.xlsx,.pptx" hidden></label><button type="button" id="pick-image" title="Add image">▧</button><span>Enter to send · Shift+Enter for newline</span></div><button class="send" type="submit" aria-label="Send">${state.sending?'■':'↑'}</button></div></form><div class="disclaimer">Claude can make mistakes. Please verify important information.</div></div></main></div>`;bind()}
function welcome(){return `<div class="welcome"><h1><img src="/claude-symbol.svg" alt="">Back at it, Ranjith S</h1><div class="suggestions"><button data-p="Explain this code step by step">✎ <b>Write</b></button><button data-p="Teach me this topic simply">◇ <b>Learn</b></button><button data-p="Help me debug this code">&lt;/&gt; <b>Code</b></button><button data-p="Give me a practical life suggestion">☕ <b>Life stuff</b></button><button data-p="Choose the best option for me">✧ <b>Claude's choice</b></button></div></div>`}
function renderMsg(m){const u=m.role==='user';return `<article class="message ${u?'user':'assistant'}" data-id="${m.id}"><div class="message-avatar">${u?'R':logo(22)}</div><div class="message-main"><div class="message-name">${u?'You':'Claude'}</div><div class="message-content">${u?esc(m.content).replaceAll('\n','<br>'):md(m.content)}</div>${m.attachments?.length?`<div class="message-files">${m.attachments.map(a=>`<span class="sent-file">▧ ${esc(a.name)}</span>`).join('')}</div>`:''}</div></article>`}
function fileChip(a){return `<div class="file-chip">${a.preview?`<img src="${a.preview}" alt="">`:'<span class="file-icon">▧</span>'}<span class="file-meta"><b>${esc(a.name)}</b><small>${a.sizeLabel}</small></span><button data-remove="${a.id}" type="button">×</button></div>`}
function bind(){$('#new')?.addEventListener('click',()=>{state.active=null;state.files=[];state.fileData.clear();render()});$('.chat-list')?.addEventListener('click',e=>{const d=e.target.closest('[data-del]')?.dataset.del;if(d){e.stopPropagation();state.chats=state.chats.filter(c=>c.id!==d);if(state.active===d)state.active=null;save();render();return}const b=e.target.closest('[data-chat]');if(b){state.active=b.dataset.chat;state.files=[];state.fileData.clear();render()}});document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const p=$('#prompt');p.value=b.dataset.p;p.focus();resize(p)});const p=$('#prompt');p?.addEventListener('input',()=>resize(p));p?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$('#composer')?.addEventListener('submit',e=>{e.preventDefault();if(state.sending)state.controller?.abort();else send()});$('#file')?.addEventListener('change',async e=>{const selected=[...e.target.files];e.target.value='';for(const f of selected){if(f.size>15*1024*1024){toast(`${f.name} is over 15 MB`);continue}try{const a=await fileRead(f);state.files.push(a);state.fileData.set(a.id,a)}catch{toast(`Could not read ${f.name}`)}}render();setTimeout(()=>$('#prompt')?.focus(),0)});$('#pick-image')?.addEventListener('click',()=>$('#file')?.click());$('.attachments')?.addEventListener('click',e=>{const id=e.target.closest('[data-remove]')?.dataset.remove;if(id){state.files=state.files.filter(x=>x.id!==id);state.fileData.delete(id);render();$('#prompt')?.focus()}});$('#clear')?.addEventListener('click',()=>{const c=chat();if(c){c.messages=[];save();render()}});$('#theme')?.addEventListener('click',()=>{localStorage.setItem(THEME,localStorage.getItem(THEME)==='light'?'dark':'light');render()});$('#model')?.addEventListener('click',()=>$('#model-menu')?.classList.toggle('hidden'));document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{state.model=b.dataset.model;save();render()});document.querySelectorAll('.copy').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.closest('.code-card').querySelector('code').textContent);b.textContent='Copied';setTimeout(()=>b.textContent='Copy',900)});$('#mobile')?.addEventListener('click',()=>$('.sidebar')?.classList.toggle('open'));$('#collapse')?.addEventListener('click',()=>$('.sidebar')?.classList.toggle('collapsed'))}
function resize(x){x.style.height='auto';x.style.height=Math.min(x.scrollHeight,220)+'px'}
function fileRead(f){return new Promise((res,rej)=>{if(!f.type.startsWith('image/')){const r=new FileReader();r.onload=()=>res({id:uid(),name:f.name,size:f.size,type:f.type||'application/octet-stream',preview:null,data:r.result,sizeLabel:formatSize(f.size)});r.onerror=rej;r.readAsDataURL(f);return}const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.72);res({id:uid(),name:f.name,size:f.size,type:'image/jpeg',preview:data,data,sizeLabel:`${Math.max(.1,(data.length*0.75)/1048576).toFixed(1)} MB`})};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(f)})}
function formatSize(n){return n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
function ensure(){let c=chat();if(!c){c={id:uid(),title:'New chat',messages:[],createdAt:Date.now()};state.chats.unshift(c);state.active=c.id}return c}
function makeContent(m){if(!m.attachments?.length)return m.content;const parts=[];if(m.content)parts.push({type:'text',text:m.content});for(const a of m.attachments){const f=state.fileData.get(a.id);if(f?.type.startsWith('image/')&&f.data)parts.push({type:'image_url',image_url:{url:f.data}});else parts.push({type:'text',text:`[Attached file: ${a.name} (${a.type||'unknown'}, ${a.sizeLabel})]`})}return parts}
async function send(){const text=$('#prompt').value.trim();if(!text&&!state.files.length)return;const c=ensure(),raw=state.files.splice(0),refs=raw.map(({id,name,size,type,sizeLabel})=>({id,name,size,type,sizeLabel}));c.messages.push({id:uid(),role:'user',content:text||'Please analyze the attached files.',attachments:refs});if(c.title==='New chat')c.title=(text||refs[0]?.name||'New chat').slice(0,48);save();state.sending=true;state.controller=new AbortController();render();scroll();const a={id:uid(),role:'assistant',content:''};c.messages.push(a);try{const messages=c.messages.filter(x=>x!==a).map(x=>({role:x.role,content:makeContent(x)}));const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:state.controller.signal,body:JSON.stringify({model:state.model,messages})});if(!r.ok){const j=await r.json().catch(()=>({}));throw Error(j.details||j.error||`Request failed (${r.status})`)}const rd=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {done,value}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});const ps=buf.split('\n\n');buf=ps.pop()||'';for(const p of ps)consume(p,a)}if(buf)consume(buf,a);if(!a.content.trim())a.content='No response was returned.';save()}catch(e){if(e.name!=='AbortError'){a.content=`**Error:** ${e.message}`;save();toast('Model request failed')}}finally{state.sending=false;state.controller=null;save();render();scroll()}}
function consume(p,m){for(const l of p.split('\n')){if(!l.startsWith('data:'))continue;const d=l.slice(5).trim();if(!d||d==='[DONE]')continue;try{const j=JSON.parse(d),delta=j.choices?.[0]?.delta?.content;if(j.error)m.content+=`\n\n**Error:** ${j.error}`;else if(typeof delta==='string'){m.content+=delta;const el=document.querySelector(`[data-id="${m.id}"] .message-content`);if(el){el.innerHTML=md(m.content);scroll()}}}catch{}}}
function scroll(){const c=$('#conversation');if(c)c.scrollTop=c.scrollHeight}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2400)}
if(!localStorage.getItem(THEME))localStorage.setItem(THEME,'dark');render();